#!/bin/bash

SOURCEDIR=$1
DESTDIR=$1

on_die()
{
    # Cleanup watch files
    echo "Cleaning up"
    find . -name '.*\.ecowatch' -exec rm -f {} \;
    exit 0
}
trap 'on_die' TERM
trap 'on_die' SIGINT

get_watch_file() {
    filename=`basename $1`
    dir=`dirname $1`
    echo "$dir/.$filename.ecowatch"
}

while true; do
    FILES=`find . -name *.eco`
    
    for f in $FILES; do
        watchfile=`get_watch_file $f`
        if [[ ! -f $watchfile || `diff $f $watchfile` ]]; then
            NAMESPACE=`echo "$f" | sed 's/.*templates\/\(.*\)\.[a-z]*eco/\1/g' | tr / .`
            DESTDIR=`dirname $f | sed 's/coffeescript/compiled-cs/'`
            mkdir -p $DESTDIR
            OUTPUT=$(eco --identifier $NAMESPACE --output $DESTDIR $f 2>&1)
            if [ $? -eq 0 ]; then
                echo "Recompiled (eco) $f into $DESTDIR"
            else
                echo "Failed to recompile $f:"
                echo $OUTPUT
            fi
            cp $f $watchfile
        fi
    done
    
    sleep 0.25
done